### ISSUE TITLE
User 'gradle' can't create directories when binding local directory with '-v'

### ISSUE THREAD

**Issue by lucasvc** [keeganwitt/docker-gradle#10]
I'm following the example from the [official repo](https://hub.docker.com/_/gradle/), in a Docker for Windows.
But I got this error:
```
$ docker run --rm -v "$PWD":/project -w /project --name gradle gradle:alpine gradle tasks
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Failed to create directory '/project/.gradle/buildOutputCleanup'
```
If I change the command for a `ls -la` the folder owner is `root` and not `gradle` ([who executes the commands](https://github.com/keeganwitt/docker-gradle/blob/7318ecf2463dfb408c3a313a9755b932d5fb8376/jdk8-alpine/Dockerfile#L43)):
```
$ docker run --rm -v //c/develop/my-folder:/project -w /project --name gradle gradle:alpine ls -la
total 8
drwxr-xr-x    2 root     root             0 Mar 31 20:06 .
drwxr-xr-x    1 root     root          4096 Mar 31 20:06 ..
-rwxr-xr-x    1 root     root           949 Mar 31 20:06 pom.xml
```

Watching other code-building and language containers: 
- [Maven](https://github.com/carlossg/docker-maven/blob/322d0dff5d0531ccaf47bf49338cb3e294fd66c8/jdk-8/Dockerfile)
- [OpenJDK](https://github.com/docker-library/openjdk/blob/445f8b8d18d7c61e2ae7fda76d8883b5d51ae0a5/8-jdk/Dockerfile)
- [Go](https://github.com/docker-library/golang/blob/132cd70768e3bc269902e4c7b579203f66dc9f64/1.8/Dockerfile)
- [Ruby](https://github.com/docker-library/ruby/blob/e98bec810e6f1bd88ad0106f2e3b3f3291f5f5bb/2.4/Dockerfile)

don't use `USER` directive. Is there any reason to use in this case?

**Comment by lucasvc** [comment]
As workaround, adding `-u root` flag works.

**Comment by keeganwitt** [comment]
I used `USER` because I think it's best practice not to run containers as root.  Many images out there do because back in the day, there was no other choice.

**Comment by keeganwitt** [comment]
I'm dreadfully sorry for the late response.  Somehow notifications got disabled on this repo and I had no idea folks were having problems.  It's back on now, but if I don't respond in the future, feel free to yell at me on [email](mailto:keeganwitt@gmail.com) or [Twitter](https://twitter.com/keeganwitt).

**Comment by lucasvc** [comment]
No problem for lating.
You're right about the good practice of using a non-root user. But volumes (AFAIK) doesn't have yet non-root user permissions.
I this is why I supose other code-builder containers still use root user.

**Comment by keeganwitt** [comment]
I guess all the systems I was testing on had uid of 1000 on the host so I didn't notice this failure.  It looks like if you're running as another uid, there's no other option in Docker currently other than running as root.

I've been noodling about this a few days now.  I'm gonna see if I can get a recommendation from the Docker Library guys, but it looks like to me there's just two options.
1. Move the container user back to root
1. Leave the `gradle` user, create a volume for both _/home/gradle/.gradle_ and _/home/root/.gradle_ and update instructions to say to run with `--user root` if the host uid is not _1000_.

The nice thing about option 2 is you may be able to run not as root.  Given your folks' usages, would one option be more preferable to another?

**Comment by beenanner** [comment]
Option 2 sounds like a good compromise to me. For my work's use-case we were planning on using namespaces for our build servers, so that even if a tool's container run as root they won't really be root on the host. We just map our container 'root' users to the 'builder' user on the host.

**Comment by keeganwitt** [comment]
Here's the PR for option 2: #24.

**Comment by keeganwitt** [comment]
yosifkit from the Docker Library team suggested symlinking _/home/gradle/.gradle_ to _/root/.gradle_ instead of defining an extra unused volume.  The other option we talked about on the PR was 1)  mentioned earlier. Officially, they have no preference between the two.  I like not running as root, but does the _/root/.gradle_ symlink seem like more confusion than it's worth?

**Comment by keeganwitt** [comment]
I've moved ahead with the symlink idea.
