### ISSUE TITLE
`git` missing in gradle:jdk11 after move to AdoptOpenJDK

### ISSUE THREAD

**Issue by mattiasr** [keeganwitt/docker-gradle#103]
openjdk:11-jdk had `git` binary bundled, the new adoptopenjdk:11-jdk-hotspot doesn't

Since we use gradle:jdk11 as default image and depends on git binary for our builds we kind of miss it.

Would be great if you could save versions of images on dockerhub so you can pinpoint a specific version.

**Comment by keeganwitt** [comment]
I'll give some thought on what the right stuff to include is.  In the mean time, you can pull the older tag using the sha.  But I agree, the non-idempotent nature of Docker tags (at least how they're typically used) often leads to situations like this.

**Comment by keeganwitt** [comment]
https://github.com/docker-library/official-images/pull/6027
