### ISSUE TITLE
Why is Gradle daemon so slow to start?

### ISSUE THREAD

**Issue by neelkamath** [keeganwitt/docker-gradle#113]
I feel like this would've been answered elsewhere, but I've genuinely searched the nets for over an hour regarding this. The daemon takes roughly three minutes to start both on my laptop, as well as on CI servers such as GitLab. I tried disabling the daemon, but that just results in the JVM being forked which is also slow (and recent versions of Gradle docs say to use the daemon even for one-time uses in things like containers, I think). So am I forgetting some JVM memory setting to add to `settings.gradle` or is it actually this slow?

**Comment by keeganwitt** [comment]
Gradle explicitly says daemons will slightly decrease performance on one-time use containers

> If you run CI builds in ephemeral environments (such as containers) that do not reuse any processes, use of the Daemon will slightly decrease performance (due to caching additional information) for no benefit, and may be disabled.

https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:why_the_daemon

Are you sure the time is actually going into starting the daemon?  It seems more likely there's something else going on. And does the same Gradle version start faster outside the Docker image (keeping in mind to account for container spin-up time)? Or perhaps in a different Docker image? If not, this question might be better suited for the [Gradle Forums](https://discuss.gradle.org/).
Sorry, this is a problem that's hard to diagnose without digging in fairly deep.

**Comment by keeganwitt** [comment]
You've probably seen this already, but in case you haven't, this might be helpful also: https://guides.gradle.org/performance/

**Comment by neelkamath** [comment]
I'm a novice in programming, so I'm not _sure sure_ of the daemon being the one that slows down the container by so much. But when trying it out locally for my simple programs, it displays that it's starting the daemon for a very long time before it actually starts compiling, etc. Since my programs are small, I feel like it wouldn't be something my build file is doing which is wrong.

Gradle runs fast locally (I am using the Gradle wrapper so it runs similarly everywhere). I initially wanted to use containers for running the tests and development server locally, but the initial startup didn't make sense for rapid iterations. So now I just run `./gradlew ...` directly cuz Gradle is pretty self-isolated anyways.

The problem isn't just the local startup time for containers, but even in CI/CD, since each job runs isolated, a few Gradle tasks (i.e., a few jobs) each get slowed down by a few minutes making it a pretty big hit.

I have no idea how to improve it though, so feel free to close this if nothing can be done in the foreseeable future, I just wanted to make sure I wasn't doing anything stupid (I've tried the build scans and stuff).

**Comment by keeganwitt** [comment]
If there is an issue, it's unlikely I can do anything about it in this project (unless it were something related to the fact the images use Ubuntu and AdoptOpenJDK; those are choices within the purview of this project). If it's an issue with Gradle itself, we'd need to seek help from someone on the Gradle team.

I would add I run a [small set](https://github.com/keeganwitt/docker-gradle/tree/master/test) of Java compilation and test execution as part of the CI for this project, to ensure everything is in working order. The [last run](https://travis-ci.org/keeganwitt/docker-gradle/jobs/581441554#L1108) took 14.45 seconds.

I'm willing to help you research, but at the moment, I have no reason to believe there's an issue with the images.

**Comment by neelkamath** [comment]
It's not an issue with Gradle because it's only slow in containers (even when I set Docker for Mac to utilize more than half my laptop's CPU and RAM). I'm not just talking about the daemon starting, but even the regular compilation processes, etc. are significantly slower in the container. I've not used any advanced Docker features so my Docker related files could probably use some tuning.

Regarding the Gradle docs on [the daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html), the section [Why the Gradle Daemon is important for performance](https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:why_the_daemon) states:
> If you run CI builds in ephemeral environments (such as containers) that do not reuse any processes, use of the Daemon will slightly decrease performance (due to caching additional information) for no benefit, and may be disabled.

While the section [Disabling the Daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:disabling_the_daemon) states:
> **Continuous integration**
Since Gradle 3.0, we enable Daemon by default and recommend using it for both developers' machines and Continuous Integration servers. However, if you suspect that Daemon makes your CI builds unstable, you can disable it to use a fresh runtime for each build since the runtime is completely isolated from any previous builds.

I'm assuming the second section isn't contradicting the first like it might seem. I'm inferring that they're talking about a single CI "job" invoking Gradle multiple times, which would explain how it isn't fully isolated because of shared caches. You must admit this is confusing for a beginner to figure out whether disabling the daemon in CI/CD pipelines is good or bad practice.

I don't know if this has anything to do with OpenJDK because I recall JDK 11 was supposed to tell the VM how to not leak memory without unlocking experimental options (e.g., no more `java -server -XX:+UnlockExperimentalVMOptions ... -jar uber.jar`). But my image still OOM'ed (Out Of Memory). Since there was _probably_ something I misunderstood in that, I'm assuming I'm doing something wrong with Gradle in Docker too. Even though I haven't figured what I am/amn't doing yet, I'll close this, since it isn't something which is immediately obvious. Thanks anyways.

**Comment by keeganwitt** [comment]
I saw that section too. And you're right, it does seem somewhat contradictory. I think their idea was that the daemon was "good enough" performance-wise that you didn't really need to disable it. I think what they mean by "unstable" is within the build itself. For example, using the daemon vs not has differences in the java processes & threads, so if you're doing some weird things with threading in your build, it may not play well with the daemon. I saw one project where that was the case, which had some fancy integration tests. I don't think they were (at least necessarily) talking about invoking Gradle multiple times in the same container.

I'll add that I've seen differences in performance on Fedora based machines vs Debian based machines due to differences in the storage driver each system uses. I never looked into what Docker for Mac is running (I assume something in the Debian family). I also don't know much about the Mac hypervisor's filesystem mounting performance.

But it sounds like this isn't just a performance issue, but your containers are being killed due to out of memory?

**Comment by neelkamath** [comment]
Nahh, the OutOfMemory error was when I don't use flags like `-XX:+UnlockExperimentalVMOptions`. I gave that example to show that there are probably other components which I've misunderstood which is why Gradle seems so slow.
I'll try playing around with using the experimental flags even for tests, and toggling filesystem sharing options a little more.
