### ISSUE TITLE
Install git-lfs please

### ISSUE THREAD

**Issue by stewartbryson** [keeganwitt/docker-gradle#114]
I use this image as my default image for all our builds, and I just recently implemented git large file support for one of our repositories.

I can build a custom image based on this image... it's not a problem, but I like using the `latest` tag with this image and knowing that my builds are always using the latest gradle.

I understand if you don't add it, but would appreciate it if you do.

Thanks.

**Comment by keeganwitt** [comment]
Hmm, this seems reasonable. I'll go ahead and add it.

**Comment by keeganwitt** [comment]
Official images PR: https://github.com/docker-library/official-images/pull/6757
