### ISSUE TITLE
Cannot resolve flatDir for local jars

### ISSUE THREAD

**Issue by maxsxu** [keeganwitt/docker-gradle#118]
Below is the project layout:

```
├── libs
│   └── local-jdk.jar
├── src
│   ├── main
│   └── test
├── build.gradle
```

and the `build.gradle`:

```
repositories {
    flatDir { dirs projectDir.toString() + '/libs' }
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'com.jsonbruce:local-jdk:1.0'
}
```

It works when I run `gradle clean build` in terminal.

But it failed via `docker run --rm -u gradle -v /project:/home/gradle/project -w /home/gradle/project gradle:5.6.3-jdk8 gradle clean build`:

Below is the errors:
```
> Task :compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.jsonbruce:local-jdk:1.0
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

It seems it cannot find the local jar in the `libs` directory,
So I guess the gradle cannot resolve `flatDir` in the container. Any help?

**Comment by jsonbruce** [comment]
An alternative way is using `fileTree`:

```
dependencies {
        implementation fileTree(dir: 'libs', include: '*.jar')
}
```

But the `flatDir` is prefered.

**Comment by keeganwitt** [comment]
I'm having trouble reproducing this.

```
.
├── build.gradle
├── libs
│   └── commons-lang3-3.9.jar
├── settings.gradle
└── src
    └── main
        └── java
            └── Main.java
```

Jar for reference: https://search.maven.org/remotecontent?filepath=org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar

_settings.gradle_
```gradle
rootProject.name = 'flatDir'
```

_build.gradle_
```gradle
plugins {
    id 'java'
}
group 'org.codehaus.groovy.docker.tests'
version '1.0-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
    flatDir { dirs projectDir.toString() + '/libs' }
//    mavenCentral()
}
dependencies {
    implementation 'org.apache.commons:commons-lang3:3.9'
}
```

`docker run --rm -u gradle -v c:/Users/Keegan/Desktop/flatDir:/home/gradle/project -w /home/gradle/project gradle:5.6.3-jdk8 gradle --no-daemon build`
```
Welcome to Gradle 5.6.3!

Here are the highlights of this release:
 - Incremental Groovy compilation
 - Groovy compile avoidance
 - Test fixtures for Java projects
 - Manage plugin versions via settings script

For more details see https://docs.gradle.org/5.6.3/release-notes.html

To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.6.3/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
> Task :clean
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :jar
> Task :assemble
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check UP-TO-DATE
> Task :build

BUILD SUCCESSFUL in 5s
3 actionable tasks: 3 executed
```

I'm suspecting volume mount permission issues. If on Windows or Mac, maybe the volume isn't shared with the VM? If on Linux, maybe the directory uid/gid isn't readable by the gradle user (1000)? (that can be checked with ` ls -dn .`).

**Comment by keeganwitt** [comment]
Also your command shows `/project` as the local path for you project (which is probably only writable by root). Maybe you did that just to obfuscate the real path. But if not, make sure that path is what you intended.

**Comment by keeganwitt** [comment]
Closing stale issue. If you feel this issue should be reopened, please leave a comment.
