### ISSUE TITLE
error: could not lock config file /home/gradle/.gitconfig: Permission denied

### ISSUE THREAD

**Issue by cah-JimShingler** [keeganwitt/docker-gradle#12]
I am using gradle container in Concourse.CI

unit-test.yml
-------------
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: latest
...

Source downloads but when it comes time to invoke gradlew, ....

I receive:

error: could not lock config file /home/gradle/.gitconfig: Permission denied

**Comment by cah-JimShingler** [comment]
Got it working, ... Based on other issues, figure on a work around.

On the Concourse Task, .... Set the user.

See unit-test.yml snippet below:

...
run:
  path: "source-code/ci/tasks/unit.sh"
  user: root
...

**Comment by keeganwitt** [comment]
I'm dreadfully sorry for the late response.  Somehow notifications got disabled on this repo and I had no idea folks were having problems.  It's back on now, but if I don't respond in the future, feel free to yell at me on [email](mailto:keeganwitt@gmail.com) or [Twitter](https://twitter.com/keeganwitt).

**Comment by keeganwitt** [comment]
I'm gonna close this and merge it into #10.  Please join the discussion there, as we'll be deciding on the appropriate fix.
