### ISSUE TITLE
Gradle 6.1 (and 6.1.1) is out

### ISSUE THREAD

**Issue by tbroyer** [keeganwitt/docker-gradle#127]
When can we expect the images to be updated?

No hurry, just trying to plan our update; was about to merge an upgrade to 6.0.1 when 6.1 was released so went to it but our CI can't build as it uses the docker images rather than the wrapper.

**Comment by keeganwitt** [comment]
I opened a MR with official images the other day (https://github.com/docker-library/official-images/pull/7345). I apologize for the delay. I had an apartment fire last week and was behind on getting stuff out the door.

**Comment by keeganwitt** [comment]
I should add, I was just going to release 6.1.1 and skip 6.1. If there are folks that need 6.1, let me know, and I can do one-off to make that available.
