### ISSUE TITLE
Failed to load native library 'libnative-platform.so' for Linux amd64

### ISSUE THREAD

**Issue by johnscancella** [keeganwitt/docker-gradle#13]
I am trying to run this for use in [ConcourseCI](https://concourse.ci/index.html) and it keeps giving me the error
`Failed to load native library 'libnative-platform.so' for Linux amd64.`
![screen shot 2017-05-19 at 2 52 16 pm](https://cloud.githubusercontent.com/assets/8711605/26262421/caf2b86c-3ca2-11e7-9715-c713b4563fb6.png)

**Comment by keeganwitt** [comment]
Which image are you trying to use?

**Comment by johnscancella** [comment]
it has been so long now I don't remember. If I recall correctly the real issue was that ConcourseCI is not developed to allow a Macintosh computer to run a linux docker so this is a very weird edge case. If I ever get around to trying this again I will reopen with the details.
