### ISSUE TITLE
gradle:5.3.1-jdk8 version is missing 

### ISSUE THREAD

**Issue by jampajeen** [keeganwitt/docker-gradle#134]
Why the old version is removed every time you update the new version?

I created my Dockerfile as -> FROM gradle:5.3.1-jdk8, it does not work anymore.

Previously I created with gradle 4 or something like that and it also removed. It is very annoying people who want to stick with a gradle version.

**Comment by keeganwitt** [comment]
I have never deleted any tag or image from Docker Hub.  I'm still able to pull the "gradle:5.3.1-jdk8" image you mentioned today.

```
docker pull gradle:5.3.1-jdk8
Unable to find image 'gradle:5.3.1-jdk8' locally
5.3.1-jdk8: Pulling from library/gradle
e79bb959ec00: Pull complete                                                                                             d4b7902036fe: Pull complete                                                                                             1b2a72d4e030: Pull complete                                                                                             d54db43011fd: Pull complete                                                                                             1a97c78dad71: Pull complete                                                                                             6dcb79eeeda4: Pull complete                                                                                             bd56246cf4fd: Pull complete                                                                                             88cea60f56c5: Pull complete                                                                                             201b2cabd5f9: Pull complete                                                                                             fcef86c52c5b: Pull complete
Digest: sha256:7f7ac52b73808425de5e187e7183073cd60f30a0f3eeb82029b1872b3f8bc4b8
Status: Downloaded newer image for gradle:5.3.1-jdk8
```

If you provide more details, I'm willing to help you troubleshoot.

**Comment by jampajeen** [comment]
At docker hub https://hub.docker.com/_/gradle
There are only 6.2.x version tags

**Comment by keeganwitt** [comment]
That page only lists that latest tags, that is those that are currently maintained. This is a fairly common practice, to avoid having an enormous tag list.

I wish Docker Hub offered a better visual way to see all the tags, but at the moment the only way I know if is to query the registry, like
https://registry.hub.docker.com/v2/repositories/library/gradle/tags/?page_size=100&page=1

**Comment by keeganwitt** [comment]
Actually, I take that back -- it looks like Docker Hub now has that feature, see https://hub.docker.com/_/gradle?tab=tags&page=1&name=5.3.1

**Comment by jampajeen** [comment]
Thank you for the link, but it seems like we can not create a Dockerfile with tag that is not listed in section "Supported tags and respective Dockerfile links" in first page.

**Comment by keeganwitt** [comment]
Something else is going on for you -- the content on that page is just [Markdown files](https://github.com/docker-library/docs/tree/master/gradle) to provide documentation, it has no impact on tags hosted on Docker Hub.

What error are you seeing?

**Comment by jampajeen** [comment]
Finally, I decide to use latest version and it is fine, thank you so much for your response. 👍

**Comment by keeganwitt** [comment]
I'm sure that's what the Gradle folks would recommend anyway.
