### ISSUE TITLE
docker container keep exiting by itself

### ISSUE THREAD

**Issue by CiciliaHelena** [keeganwitt/docker-gradle#137]
Hi,

I'm trying to run a docker container using the latest tag
`docker run -ti --name gradletest gradle:latest`
and after a while, it exited by itself so I tried to start again with
`docker start gradletest -a`
it then gave me this logs and exited again.

> Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
Task :help
Welcome to Gradle 6.3.
To run a build, run gradle <task> ...
To see a list of available tasks, run gradle tasks
To see a list of command-line options, run gradle --help
To see more detail about a task, run gradle help --task <task>
For troubleshooting, visit https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 7s
1 actionable task: 1 executed

I've also tried to use 6.3.0-jdk11, but it gave me the same result.
Please advice.
Thank you.

**Comment by keeganwitt** [comment]
I take it you figured it out?  The default command doesn't run any Gradle tasks, and once you provide a task for it to run, it will exit after the task(s) complete.  It's not like a server that runs a continuous process...

**Comment by CiciliaHelena** [comment]
Yeah just realize that after a while. Thank you for getting back to me on this matter. =)
