### ISSUE TITLE
Failed to create parent directory '/project/.gradle' when creating directory 

### ISSUE THREAD

**Issue by gadieichhorn** [keeganwitt/docker-gradle#14]
## env:
- win 10 
- docker for windows

## command
docker run --rm -v .:/project -w /project --name gradle gradle:3.4-jdk8 gradle test

## error
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Failed to create parent directory '/project/.gradle' when creating directory '/project/.gradle/buildOutputCleanup'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.848 secs

**Comment by shashidesai** [comment]
seeing same issue - any workaround for this ?

**Comment by keeganwitt** [comment]
I'm dreadfully sorry for the late response.  Somehow notifications got disabled on this repo and I had no idea folks were having problems.  It's back on now, but if I don't respond in the future, feel free to yell at me on [email](mailto:keeganwitt@gmail.com) or [Twitter](https://twitter.com/keeganwitt).

**Comment by keeganwitt** [comment]
I'm gonna close this and discuss the appropriate fix in #10.  Please join the discussion there.
