### ISSUE TITLE
Do not hard code checksums in docker files

### ISSUE THREAD

**Issue by dje1990** [keeganwitt/docker-gradle#140]
Why are the sha256 checksums hard-coded in the docker files? why not download them and save the maintainers the effort of updating the checksums manually?

instead of (as seen at https://github.com/keeganwitt/docker-gradle/blob/master/jre14/Dockerfile):
```
ENV GRADLE_VERSION 6.3
ARG GRADLE_DOWNLOAD_SHA256=038794feef1f4745c6347107b6726279d1c824f3fc634b60f86ace1e9fbd1768
RUN set -o errexit -o nounset \
    && echo "Downloading Gradle" \
    && wget --no-verbose --output-document=gradle.zip "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" \
    \
    && echo "Checking download hash" \
    && echo "${GRADLE_DOWNLOAD_SHA256} *gradle.zip" | sha256sum --check - \
    \
```

use:
```
ENV GRADLE_VERSION 6.3
RUN set -o errexit -o nounset \
    && echo "Downloading Gradle" \
    && wget --no-verbose --output-document gradle.zip "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" \
    && ls -larth \
    \
    && echo "Downloading Gradle checksum hash" \
    && wget --no-verbose --output-document gradle.zip.sha256 "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip.sha256" \
    && ls -larth \
    \
    && echo "Checking download hash" \
    && echo $(echo "$(cat gradle.zip.sha256) *gradle.zip" | sha256sum -c) \
    \
```

**Comment by dje1990** [comment]
The above code snippet has been tested in my personal build at:
https://hub.docker.com/layers/dje1990/zulu-alpine-gradle/0.0.2/images/sha256-86f881a39baf5bcf8b182770a4b785b39b8c04a2dad7cbc642e24c3bf5e9822f?context=repo

**Comment by keeganwitt** [comment]
The Docker Library team [stated](https://github.com/docker-library/official-images/pull/4859#issuecomment-423336355) they preferred hard-coding the values, rather than having the sha configured during the build process (downloading a checksum file, programmatically setting an environment variable, etc), so that if somehow the Gradle download server was compromised, the checksum would fail in later Docker builds.

**Comment by dje1990** [comment]
Good to know, thanks for the explanation. Feel free to close this ticket. Thanks.
