### ISSUE TITLE
Unable To Use JDK 8 on ARM 

### ISSUE THREAD

**Issue by heywoodlh** [keeganwitt/docker-gradle#153]
This is more of a clarifying question vs an issue. 

I wanted to use [gradle:jdk8](https://hub.docker.com/layers/gradle/library/gradle/jdk8/images/sha256-0f36e25464ee598632ea62acb9456d2357bb7a8d572cc0b8faaf492bbbb05d91?context=explore) as the base for an ARM/x86_64 bit image. I noticed that particular tag doesn't have a compatible image for any ARM architectures. 

My question is why isn't the  gradle:jdk8 tag available for ARM whereas the other tags have ARM as a target? The Dockerfile for jdk8 seems to build just fine for ARM (I built it on ARM v7 and ARM64).

**Comment by keeganwitt** [comment]
At the time, Java 8 didn't have ARM images available that the upstream official image ([adoptopenjdk](https://hub.docker.com/_/adoptopenjdk)).  I'm forgetting exactly why that was at the moment.  However, looking at the list of tags no, it appears that it is now available.

I've created a MR to update the builds: https://github.com/docker-library/official-images/pull/8758

**Comment by keeganwitt** [comment]
They should be available now.

**Comment by heywoodlh** [comment]
Sweet, thanks for the quick response!
