### ISSUE TITLE
gradle 4.0 in docker hub

### ISSUE THREAD

**Issue by windhc** [keeganwitt/docker-gradle#16]
Hi! When could find gradle 4.0 in docker hub?
Thinks!

**Comment by andrewklau** [comment]
The 3.5 tags seem to be pointing to 4.0

**Comment by keeganwitt** [comment]
I fixed the 3.5 mislabel (https://github.com/docker-library/official-images/pull/3183). 4.0 is now up.

**Comment by keeganwitt** [comment]
I'm dreadfully sorry for the late response.  Somehow notifications got disabled on this repo and I had no idea folks were having problems.  It's back on now, but if I don't respond in the future, feel free to yell at me on [email](mailto:keeganwitt@gmail.com) or [Twitter](https://twitter.com/keeganwitt).
