### ISSUE TITLE
Consider mirroring the container image to quay.io (or alternatives)

### ISSUE THREAD

**Issue by chgl** [keeganwitt/docker-gradle#168]
Due to the recent rate-limits introduced by Docker Hub, it would be great id the gradle image could be mirrored to quay.io (or any alternative public registry) as well.

**Comment by keeganwitt** [comment]
I'll have to give some thought how to do that. Part of the complication is that the Docker Library folks may push new versions of the same tag (for example when there's a security update to the base image). I'm not actually sure how often that happens in practice (I suspect probably not very often though).
I could trigger the copy myself (maybe with Skopeo or something) when I make updates, but it'd miss out on those potential upstream updates.

**Comment by keeganwitt** [comment]
I see this exists now. How'd it get set up?

https://quay.io/repository/official-images/gradle

**Comment by chgl** [comment]
Ha, I didn't know about that. it seems to be just a mirror of all "library"/official images.

 I believe as an official image gradle is excluded from rate limiting anyways, so my original point is no longer valid which is why I closed the issue. But yes, that mirror is actually another solution.
