### ISSUE TITLE
3.5 tag gets gradle 4.0

### ISSUE THREAD

**Issue by andrewklau** [keeganwitt/docker-gradle#17]
Dockerhub 3.5 tags are pulling down gradle 4.0 which ended up breaking a CI test as it was checking for 3.5

**Comment by k-nakayama-pg** [comment]
I also had the same problem.
I want tags to be separated by gradle 4.0 and gradle 3.5

**Comment by krzysiekruczaj** [comment]
The same happened for me :+1:

**Comment by riendeau** [comment]
This is breaking my build as well, as we're currently using the deprecated jetty plugin, which is present in 3.5 but removed in 4.0.

**Comment by andrewklau** [comment]
gradle wrapper is good :+1:

**Comment by keeganwitt** [comment]
Sorry for the late reply -- for some reason I didn't get an email for this issue.  I mislabeled 3.5 as 4.0.  This has been corrected https://github.com/docker-library/official-images/pull/3183.

**Comment by keeganwitt** [comment]
Oh, are you still using 3.5?  I hadn't pushed 3.5.1.

**Comment by keeganwitt** [comment]
I'm dreadfully sorry for the late response.  Somehow notifications got disabled on this repo and I had no idea folks were having problems.  It's back on now, but if I don't respond in the future, feel free to yell at me on [email](mailto:keeganwitt@gmail.com) or [Twitter](https://twitter.com/keeganwitt).
