### ISSUE TITLE
`6.8.0` images are tagged with `6.7` prefixes

### ISSUE THREAD

**Issue by gfjalar** [keeganwitt/docker-gradle#173]
In the recent release, the new images tags were correctly updated from `6.7.1` to `6.8.0` BUT the `6.7` tags were left intact.

I've prepared the fix for this here: https://github.com/keeganwitt/docker-library-official-images/pull/1

**Comment by keeganwitt** [comment]
Shoot. My apologies.

I've opened this MR to re-tag 6.7: https://github.com/docker-library/official-images/pull/9473
Then this MR after it to tag 6.8 properly: https://github.com/docker-library/official-images/pull/9474

**Comment by keeganwitt** [comment]
6.7 has been re-tagged, the 6.8 builds should be triggered shortly.

**Comment by gfjalar** [comment]
Perfect :) Thank you so much :)
