### ISSUE TITLE
How to setup proxy?

### ISSUE THREAD

**Issue by dlubomski** [keeganwitt/docker-gradle#177]
How to setup proxy for gradle inside this docker?

**Comment by keeganwitt** [comment]
I'm not sure the use case you're trying to solve, but I'd think you'd configure Docker to use a proxy, see https://docs.docker.com/network/proxy/.

**Comment by kokaia** [comment]
ARG PROXY_HOST
ARG PROXY_PORT

RUN  --mount=type=cache,target=/root/.gradle/caches  /usr/bin/gradle -Dorg.gradle.daemon=false \
   -Dhttp.proxyHost=$PROXY_HOST -Dhttp.proxyPort=$PROXY_PORT \
   -Dhttps.proxyHost=$PROXY_HOST -Dhttps.proxyPort=$PROXY_PORT \
   -Dhttp.nonProxyHosts="localhost|10.1.1.1" \

**Comment by keeganwitt** [comment]
Closing stale issue. If you feel this issue should be reopened, please leave a comment.
