### ISSUE TITLE
link question

### ISSUE THREAD

**Issue by timchenxiaoyu** [keeganwitt/docker-gradle#19]
why use  ln -s "${GRADLE_HOME}/bin/gradle" /usr/bin/gradle \
rather than cp gradle to /usr/bin  ????

**Comment by keeganwitt** [comment]
It seemed logical to me to keep all the binaries together rather than copying the launcher to bin.  I've seen both patterns used.  Do you know of any documented best practices?

**Comment by timchenxiaoyu** [comment]
some people may docker run -v to overlay  /opt dir ,so I suggest cp binaries to /usr/bin/

**Comment by keeganwitt** [comment]
Can you explain the overlay use case?  I've never mounted a volume on the same directory the container's binaries are written.  Will that overwrite the jars, etc in the Gradle installation in _/opt_?

**Comment by keeganwitt** [comment]
Closing stale issue.  Feel free to request it be reopened to continue the discussion.
