### ISSUE TITLE
How to preserve Gradle cache in the Docker image?

### ISSUE THREAD

**Issue by bohdan-qa** [keeganwitt/docker-gradle#190]
I build a docker image from `gradle:6.8.3-jdk11` and there's a step in my Dockerfile:
`RUN gradle compileTestJava`
which, among other things, downloads project dependencies into `.gradle/caches`

Since `/home/gradle/.gradle` declared a volume in a base image,`.gradle` folder gets cleared. So all the dependencies have to be redownloaded for every container.

Is it possible to unmount this volume using a Dockerfile, or is there any other way to preserve gradle cache in the image?

**Comment by autaut03** [comment]
Did you figure this out? It's insane how hard it is to get cache working

**Comment by bohdan-stroi** [comment]
> I don't understand how this would do anything at all. This is already present in the Dockerfile
> 
> [docker-gradle/jdk21-noble/Dockerfile](https://github.com/gradle/docker-gradle/blob/df74d6e72237e42d11f620a2eb645697c59a9b57/jdk21-noble/Dockerfile#L78)
> 
> Line 78 in [df74d6e](/gradle/docker-gradle/commit/df74d6e72237e42d11f620a2eb645697c59a9b57)
> 
>  && ln --symbolic "${GRADLE_HOME}/bin/gradle" /usr/bin/gradle 
> 

Right, I copied the wrong line from the Dockerfile. I've updated my initial response with the correct solution.
