### ISSUE TITLE
JDK 17 image

### ISSUE THREAD

**Issue by tlf30** [keeganwitt/docker-gradle#197]
Hello,
I know this is probably be blocked by #194, but it would be great to get JDK 17 images available. 

Thanks,
Trevor

**Comment by keeganwitt** [comment]
That's correct, it's blocked on changing the base image. There was no 17 release of adoptopenjdk base image. I think I'm not really gonna have any other choice but to drop openj9 support. I've been dragging my feet on this because I hated to put users through yet another change in base image and I wanted to be sure Temurin is the right path and not openjdk or something else.

It sucks to go through this again (previously moved from openjdk to adoptopenjdk), but at the moment it's feeling like eclipse-temurin is the way to go.

**Comment by tlf30** [comment]
I agree, but I too wish this transition to Temurin was less painful. Loosing openj9 and the jre builds at the same time took a hit on us for our projects. We are looking into alternatives for non-container installs to get a jre now. They want everyone to use jlink, but that does not work for every situation. I imagine that their docker image is jdk based, and not jre based, which for this project is not an issue, but it will be for others including myself shortly.

**Comment by keeganwitt** [comment]
Do you have a use case for Gradle with JRE? Or were you talking about as a prod runtime?

**Comment by tlf30** [comment]
No talking about prod. Just me ranting about another thing that Temurin is impacting 😄

**Comment by keeganwitt** [comment]
Gotcha. I ask because I have JRE images of Gradle, but now I'm thinking those probably aren't needed (at the time I thought they might be useful for people doing native builds), but this whole jlink thing makes it confusing what a JRE image would mean anymore.

**Comment by keeganwitt** [comment]
Actually, I misread the conclusion of that GH issue -- They do plan on making JRE images. 8 and 11 are out now, and presumably they are working on 17. Still, I'm thinking they may not make sense for this image. Please speak up if you think differently.

**Comment by tlf30** [comment]
I agree that it probably does not make sense for this image. I will have to go back and reread the issues at adoptium. Iirc they were going to do 8 and 11 but not 17, but I may be wrong as it was quite a confusing swt of issues they have.

**Comment by keeganwitt** [comment]
I didn't see them mention 17, but it was also for July and they were still working on 16.

https://github.com/adoptium/adoptium/issues/68

**Comment by keeganwitt** [comment]
Maybe they changed their minds. This newer thread says they _won't_ be doing JREs, even though there are some out there already.

https://github.com/adoptium/adoptium/issues/74

**Comment by tlf30** [comment]
Yeah, it is quite confusing. They have different issues with conflicting info. I think 74 is the most accurate at this point.
