### ISSUE TITLE
Creating the gradle user does not guarantee the population of the env var $HOME

### ISSUE THREAD

**Issue by mdelapenya** [keeganwitt/docker-gradle#20]

**Comment by keeganwitt** [comment]
In Debian? Alpine? Or both?

**Comment by mdelapenya** [comment]
Hi @keeganwitt, I used `gradle:jdk-alpine`. I checked that, not only the env var, also the gradle user HOME is not created

**Comment by keeganwitt** [comment]
How did you test?
``` docker run --rm -it gradle:jdk-alpine sh~
$ echo $HOME
/home/gradle
~ $ cd ~
~ $ pwd
/home/gradle```

**Comment by keeganwitt** [comment]
Since I'm not presently aware of an issue, I'm gonna go ahead and close this issue.  If you're aware of an ongoing problem, let me know and we can reopen it.
