### ISSUE TITLE
7.3.1 image has missing OS/Arch

### ISSUE THREAD

**Issue by SnakeSVx** [keeganwitt/docker-gradle#204]
Updating from the 7.3 to 7.3.1 images failes because of missing OS/arch specifications.

If you compare 7.3 to 7.3.1 you notice that while 7.3 has support for about 5 archs, 7.3.1 has been reduced to 1.

https://hub.docker.com/layers/gradle/library/gradle/7.3-jdk11/images/sha256-30162a20bb304979ea8455433d60f87128e2655447c0e0b91926240081cdace9?context=explore

Supports: linux/s390x, linux/amd64, linux/ppc64Ie, linux/arm/v7, linux/arm64/v8

https://hub.docker.com/layers/gradle/library/gradle/7.3.1-jdk11/images/sha256-30162a20bb304979ea8455433d60f87128e2655447c0e0b91926240081cdace9?context=explore

Supports: linux/s390x

**Comment by keeganwitt** [comment]
It looks like the Jenkins builds (maintained by the Docker Library folks) are stuck except for s390x. See

- [amd64](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/gradle/)
- [s390x](https://doi-janky.infosiftr.net/job/multiarch/job/s390x/job/gradle/)
- [arm32v7](https://doi-janky.infosiftr.net/job/multiarch/job/arm32v7/job/gradle/)
- [arm64v8](https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/gradle/)
- [ppc64le](https://doi-janky.infosiftr.net/job/multiarch/job/ppc64le/job/gradle/)

I'll reach out to them.

**Comment by keeganwitt** [comment]
Builds finished now and images appear present.

**Comment by SnakeSVx** [comment]
Thanks for fixing the problem :)
