### ISSUE TITLE
amd64 version missing of gradle:6.9.2-jdk11

### ISSUE THREAD

**Issue by vbode** [keeganwitt/docker-gradle#207]
We are missing the amd64 arch for gradle:6.9.2-jdk11. 
We've checked the pipeline mentioned in below issue, and it seems to be stuck. Thanks for your help!

Similar to issue: https://github.com/keeganwitt/docker-gradle/issues/172

**Comment by Mazgis47** [comment]
I see also:
docker pull gradle:6.9.2-jdk11-alpine
6.9.2-jdk11-alpine: Pulling from library/gradle
no matching manifest for linux/amd64 in the manifest list entries
docker pull gradle:6.9.2-jdk8
6.9.2-jdk8: Pulling from library/gradle
no matching manifest for linux/amd64 in the manifest list entries

However, these are ok:
docker pull gradle:6.9-jdk8
docker pull gradle:6.9-jdk11-alpine

**Comment by maarten-donderwinkel** [comment]
> I see also: docker pull gradle:6.9.2-jdk11-alpine 6.9.2-jdk11-alpine: Pulling from library/gradle no matching manifest for linux/amd64 in the manifest list entries docker pull gradle:6.9.2-jdk8 6.9.2-jdk8: Pulling from library/gradle no matching manifest for linux/amd64 in the manifest list entries
> 
> However, these are ok: docker pull gradle:6.9-jdk8 docker pull gradle:6.9-jdk11-alpine

The older builds did succeed and the newest builds haven't for the right architecture due to the hanging build.

**Comment by keeganwitt** [comment]
From time to time, this seems to happen with the infrastructure maintained by the Docker Library team. It happened most recently in #204. It looks like the builds for amd64 and arm3v7 haven't completed yet. See
It looks like the Jenkins builds (maintained by the Docker Library folks) aren't complete except for s390x. See

- [amd64](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/gradle/)
- [arm32v7](https://doi-janky.infosiftr.net/job/multiarch/job/arm32v7/job/gradle/)
- [arm64v8](https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/gradle/)
- [ppc64le](https://doi-janky.infosiftr.net/job/multiarch/job/ppc64le/job/gradle/)
- [s390x](https://doi-janky.infosiftr.net/job/multiarch/job/s390x/job/gradle/)

**Comment by maarten-donderwinkel** [comment]
The issue is resolved for the amd64 pipeline

**Comment by keeganwitt** [comment]
All the architectures should be published now.
