### ISSUE TITLE
A little warning when build image with Gradle arm32v7

### ISSUE THREAD

**Issue by Yggdrasil80** [keeganwitt/docker-gradle#209]
Here the image with the warning :3
![image](https://user-images.githubusercontent.com/56512795/149663197-bd34e76a-517a-438f-9c74-06bda00eb3a0.png)

**Comment by keeganwitt** [comment]
Extracted text from screenshot, for searching & quoting purposes.
> WARNING: Pulled image with specified platform (linux/arm32v7), but the resulting image's configured platform (linux/arm/v7) does not match.
> This is most likely caused by a bug in the build system that created the fetched image (arm32v7/gradle:7.3.3-jdk8).
Please notify the image author to correct the configuration.

What was the pull command you used please?

**Comment by Yggdrasil80** [comment]
I use it in my Dockerfile, in the FROM part, so i suppose the command was simply "docker pull arm32v7/gradle:7-3-3-jdk8"

**Comment by keeganwitt** [comment]
Are you running this on an M1 Mac? Something else? Are you able to pull the image specifying the architecture like ` docker pull --platform linux/arm/v7 gradle:7.3.3-jdk8`?

**Comment by Yggdrasil80** [comment]
I run this from Github Actions so its on Azure classic servers. But i forgot the wokflow run ans im not able to give you more info. Sorry

**Comment by keeganwitt** [comment]
I was able to pull the image on Arm64 on Travis. If you know of another easy way to test Arm, let me know. I don't own any Arm hardware personally. I'll probably have to get a self-hosted runner setup somewhere and run against that I suppose.

https://github.com/keeganwitt/gradle-on-arm-tests
https://app.travis-ci.com/github/keeganwitt/gradle-on-arm-tests/builds/245610034
