### ISSUE TITLE
Error: Could not find or load main class jdk.compiler.com.sun.tools.javac.api=ALL-UNNAMED Caused by: java.lang.ClassNotFoundException: jdk.compiler.com.sun.tools.javac.api=ALL-UNNAMED

### ISSUE THREAD

**Issue by sanjay4finxflo** [keeganwitt/docker-gradle#214]
GRADLE_OPTS="-D--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports
  jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports
  jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports
  jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED" ./gradlew --console=plain
  --build-cache build -g="$GRADLE_USER_HOME" --rerun-tasks test

**Comment by keeganwitt** [comment]
1. What Docker image are you using? If you are using the Gradle wrapper (gradlew), there's no need to use the [gradle image](https://hub.docker.com/_/gradle). You can use any Java Docker image.
1. Both of these options work for me.
    1.  `docker run --rm -u gradle -v "$PWD":/home/gradle/project -w /home/gradle/project -e GRADLE_OPTS="--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED" gradle gradle tasks`
    1.  `docker run --rm -u gradle -v "$PWD":/home/gradle/project -w /home/gradle/project gradle gradle -Dorg.gradle.jvmargs="--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED" tasks`

**Comment by sanjay4finxflo** [comment]
yep thanks for the help, i was doing some mistake in my build script, the issue is resolved.
