### ISSUE TITLE
Vulnerabilities in 7.4.2-jdk17

### ISSUE THREAD

**Issue by kaynat12** [keeganwitt/docker-gradle#220]
Hi, tag 7.4.2-jdk17 is showing recent Ubuntu vulnerabilities, could it be fixed?

**Comment by keeganwitt** [comment]
I don't handle security updates, the Docker Library team does. It's possible they've already made the fix but one of the Jenkins jobs didn't publish a new image. Do you know what vulnerabilities? Is eclipse-temurin:17-jdk also vulnerable? Is ubuntu:20.04?

**Comment by kaynat12** [comment]
@keeganwitt  I could see following vulnerabilities

Ubuntu Security Notification for OpenLDAP Vulnerability (USN-5424-1)
Ubuntu Security Notification for PCRE Vulnerabilities (USN-5425-1)
Ubuntu Security Notification for curl Vulnerabilities (USN-5412-1)
Ubuntu Security Notification for SQLite Vulnerability (USN-5403-1)
Ubuntu Security Notification for Open Secure Sockets Layer (OpenSSL) Vulnerabilities (USN-5402-1)
Ubuntu Security Notification for libsepol Vulnerabilities (USN-5391-1)

**Comment by kaynat12** [comment]
@keeganwitt Also could you share how to connect with Docker Library team?

**Comment by keeganwitt** [comment]
You can ask in the community Slack (https://dockr.ly/slack), but the best way is probably to create an issue (https://github.com/docker-library/official-images/issues). The documentation page (https://docs.docker.com/docker-hub/official_images/) also mentions #docker-library on [Libera.Chat IRC](https://libera.chat/), though I've not used that before personally.

**Comment by keeganwitt** [comment]
I'll reach out to them and ask them for help on this issue.

**Comment by tianon** [comment]
Some of those are in `ubuntu:20.04` itself, so I've poked some Canonical folks about doing a bump to `ubuntu` (which would then trickle down here).

**Comment by keeganwitt** [comment]
Yeah, I ran `docker build`, and even on a fresh image `docker scan` still showed these issues. So I'm not sure if the packages have been patched in Ubuntu.

**Comment by kaynat12** [comment]
@keeganwitt @tianon , I could see the tag was updated 7 days ago, still we are seeing 3 vulnerabilities, 

Ubuntu Security Notification for dpkg Vulnerability

Ubuntu Security Notification for Subversion Vulnerabilities
Ubuntu Security Notification for PCRE Vulnerabilities

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/12570 should resolve those :+1:

**Comment by keeganwitt** [comment]
Closing, as this has now been completed.
