### ISSUE TITLE
gradle:7.4-jdk17 Java fails to start

### ISSUE THREAD

**Issue by nikortel** [keeganwitt/docker-gradle#221]
Gradle 4.2 tag Java started to fail today (2022-05-27)

How to reproduce:
`docker run --rm gradle:7.4-jdk17 java -version`

Result:
```
[0.003s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /home/gradle/hs_err_pid1.log
```

gradle:7.4.1-jdk17 works:
`docker run --rm gradle:7.4.1-jdk17 java -version`
```
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
```

**Comment by nikortel** [comment]
Seems to be actually an issue with eclipse-temurin:17-jdk which the Gradle image is based on

**Comment by nikortel** [comment]
Created an issue about this to adoptium: https://github.com/adoptium/containers/issues/214

**Comment by nikortel** [comment]
Update Docker from 20.10.3 to 20.10.16 solved the issue

**Comment by keeganwitt** [comment]
This issue has come up so frequently (#222, #223, #224, #226, #227, #228, #229, #230, #231), I've created a page explaining: https://github.com/keeganwitt/docker-gradle/wiki/Troubleshooting:-JAVA_HOME-is-set-to-an-invalid-directory. Please let me know how the page can be improved.
