### ISSUE TITLE
Shell not found

### ISSUE THREAD

**Issue by sebasira** [keeganwitt/docker-gradle#223]
I've been using the images here for many years, with GitLab CI/CD.

I even used them last week, but today I'm getting:

> shell not found

with `gradle:jdk11` and also `gradle:jdk8`

Here are the GitLab Job logs:

```
Running with gitlab-runner 14.1.0
  on runner-xxxxxxx
Preparing the "docker" executor
Using Docker executor with image gradle:jdk8 ...
Pulling docker image gradle:jdk8 ...
Using docker image sha256:7dd7794171495be672ae97a060eb50080c12d5268173b732f743b71b692d17e7 for gradle:jdk8 with digest gradle@sha256:8e433f41e074a52b8c4a18080bead7ca3f12a18c1a3f1e2c2e50eede1651fbb5 ...
Preparing environment
Running on runner-xxxxxxx via my-server...
Getting source from Git repository
Fetching changes...
Reinitialized existing Git repository in git-path
Checking out 32198ac as master...
Skipping Git submodules setup
Executing "step_script" stage of the job script
Using docker image sha256:7dd7794171495be672ae97a060eb50080c12d5268173b732f743b71b692d17e7 for gradle:jdk8 with digest gradle@sha256:8e433f41e074a52b8c4a18080bead7ca3f12a18c1a3f1e2c2e50eede1651fbb5 ...
shell not found
Cleaning up file based variables
ERROR: Job failed: exit code 1
```

**Comment by cookabc** [comment]
I met the same issue, anyone know what happened?

**Comment by cookabc** [comment]
> I met the same issue, anyone know what happened?

I changed image to an older version `image: gradle:7.4.1-jdk11`, and it works

**Comment by sebasira** [comment]
Thanks @cookabc I'll try that. I was using `openjdk:11` to resolve it

**Comment by keeganwitt** [comment]
It looks like Temurin must have pushed a broken image, which triggered a new gradle image to be pushed. Can you try again? It appears to be working for me now.

**Comment by duxinxiao** [comment]
gradle:jdk11 still cant work. it show that image was pushed 3 days ago.

**Comment by keeganwitt** [comment]
My test Gradle project succeeds on all the below images.

```
REPOSITORY        TAG             IMAGE ID       CREATED       SIZE
gradle            jdk17           fb4ec379092c   3 days ago    748MB
gradle            jdk11           71e215cc8b38   3 days ago    727MB
gradle            jdk8            7dd779417149   3 days ago    609MB
```

**Comment by GyllingSW** [comment]
@keeganwitt - This is from our Gitlab server - Running using 7.4.2-jdk11

`Running with gitlab-runner 13.12.0 (7a6612da)
  on Docker runner gpiAmEx4
Preparing the "docker" executor
00:03
Using Docker executor with image gradle:7.4.[2](https://skat.git.csc.dk/esle/esleinternapi/-/jobs/2163#L2)-jdk11 ...
Pulling docker image gradle:7.4.2-jdk11 ...
Using docker image sha256:71e215cc8b[3](https://skat.git.csc.dk/esle/esleinternapi/-/jobs/2163#L3)8fa2[4](https://skat.git.csc.dk/esle/esleinternapi/-/jobs/2163#L4)9[5](https://skat.git.csc.dk/esle/esleinternapi/-/jobs/2163#L5)45184caba183fae8fc1f3f7189daab5[6](https://skat.git.csc.dk/esle/esleinternapi/-/jobs/2163#L6)a19dcf847079db for gradle:7.4.2-jdk11 with digest gradle@sha256:db25faa6250d980931091d5b6101ee34076d2645bddd7e5f6daf547681a85aba ...
Preparing environment
00:01
Running on runner-gpiamex4-project-895-concurrent-0 via 7f33ccf7c9ab...
Getting source from Git repository
00:02
$ git config --global http.proxy $HTTP_PROXY; git config --global https.proxy $HTTPS_PROXY
Fetching changes with git depth set to 50...
Reinitialized existing Git repository in /builds/esle/esleinternapi/.git/
Checking out 3d59a4f1 as master...
Removing .gradle/caches/
Skipping Git submodules setup
Restoring cache
00:06
Checking cache for default...
No URL provided, cache will not be downloaded from shared cache server. Instead a local version of cache will be extracted. 
Successfully extracted cache
Executing "step_script" stage of the job script
00:01
Using docker image sha256:71e215cc8b38fa249545184caba183fae8fc1f3f7189daab56a19dcf847079db for gradle:7.4.2-jdk11 with digest gradle@sha256:db25faa6250d980931091d5b6101ee34076d2645bddd7e5f6daf547681a85aba ...
shell not found
ERROR: Job failed: exit code 1`

And attached as image

![image](https://user-images.githubusercontent.com/11475025/171040534-54d8ef47-a451-48a4-904a-da1fbd12135e.png)

**Comment by keeganwitt** [comment]
I can't tell what the breaking use case is here. Were you running a `gradle test` in this pipeline? On what architecture? Were you trying to run a shell script? If so, was it on a different shell other than Bash?

**Comment by GyllingSW** [comment]
> I can't tell what the breaking use case is here. Were you running a `gradle test` in this pipeline? On what architecture? Were you trying to run a shell script? If so, was it on a different shell other than Bash?

We never get to run anything from the setup below, which works when changed to using gradle:7.4.1-jdk11, so it fails during initialization on the build server.

`image: gradle:7.4.2-jdk11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export SPRING_CLOUD_KUBERNETES_ENABLED=false

stages:
  - build
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build-job:
  only:
    - master
  stage: build
  script:
    - gradle cibuild

test-job:
  only:
    - master
  stage: test
  script:
    - gradle citest
  artifacts:
    name: esleinternapi-"$CI_JOB_NAME"
    when: always
    paths:
      - build/reports
    reports:
      junit: build/test-results/test/**/TEST-*.xml

**Comment by keeganwitt** [comment]
Temurin's upgrade to Jammy seems to have caused a number of issues (that's all that's changed recently). Some people were saying this error was caused by a cert issue, requiring a new Docker version.

I guess what I'm gonna have to do is publish both a Focal and a Jammy version until this all gets sorted out.

**Comment by keeganwitt** [comment]
I'm working on getting `-focal` variants added: https://github.com/docker-library/official-images/pull/12543.

I didn't anticipate so much trouble coming from Temurin's Ubuntu upgrade. I apologize for the inconvenience.

**Comment by sebasira** [comment]
I'm still having the same issue

**Comment by keeganwitt** [comment]
Did you switch to one of the Focal images?

**Comment by sebasira** [comment]
How should I change it? I'm using `gradle:jdk11`

**Comment by keeganwitt** [comment]
It will be, yes. I just realized I missed creating those tags. I'll fix that today and get another PR out. Sorry about that.

**Comment by keeganwitt** [comment]
Here's the PR to add the 11 Focal tags: https://github.com/docker-library/official-images/pull/12583

**Comment by sebasira** [comment]
Thank you it works with `gradle:jdk11-focal`

**Comment by keeganwitt** [comment]
This issue has come up so frequently (#221, #222, #224, #226, #227, #228, #229, #230, #231), I've created a page explaining: https://github.com/keeganwitt/docker-gradle/wiki/Troubleshooting:-JAVA_HOME-is-set-to-an-invalid-directory. Please let me know how the page can be improved.
