### ISSUE TITLE
JVM fails to start on GitLab runner

### ISSUE THREAD

**Issue by clayly** [keeganwitt/docker-gradle#226]
This Dockerfile:
```
FROM gradle:7-jdk17
RUN java -XshowSettings:system --version
```
And this Dockerfile:
```
FROM eclipse-temurin:17-jdk-jammy
RUN java -XshowSettings:system --version
```

Fails on GitLab (runner using Docker to build Docker) with following error:
```
RUN java  -XshowSettings:system --version
[0.003s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
```

While for example this Dockerfile works ok:
```
FROM amazoncorretto:17
RUN java -XshowSettings:system --version
```

I think it somehow connected with recent changes, because all was OK month ago.

**Comment by clayly** [comment]
Source of problem is https://github.com/adoptium/containers/issues/219, closing.

**Comment by keeganwitt** [comment]
Just to link related issues, #227 (which has a longer discussion) is also about this same issue.

**Comment by keeganwitt** [comment]
This issue has come up so frequently (#221, #222, #223, #224, #227, #228, #229, #230, #231), I've created a page explaining: https://github.com/keeganwitt/docker-gradle/wiki/Troubleshooting:-JAVA_HOME-is-set-to-an-invalid-directory. Please let me know how the page can be improved.
