### ISSUE TITLE
gradle:7-jdk11 still broken on CICD tool

### ISSUE THREAD

**Issue by DyBrenn** [keeganwitt/docker-gradle#227]
docker pull gradle:7-jdk11 still returns JAVA_HOME error when running jenkins pipeline

`14:09:21  Step 1/10 : FROM gradle:7-jdk11 as build
14:09:21   ---> 7cfb30dae0e3
14:09:21  Step 2/10 : WORKDIR /app
14:09:23   ---> Running in 1b5f1324a2e6
14:09:27  Removing intermediate container 1b5f1324a2e6
14:09:27   ---> 2ad0c160d7b4
14:09:27  Step 3/10 : COPY build.gradle gradle.properties settings.gradle /app/
14:09:29   ---> 6ce0cadf269f
14:09:29  Step 4/10 : RUN gradle clean build --no-daemon > /dev/null 2>&1 || true
14:09:29   ---> Running in 3dcb0db26182
14:09:34  Removing intermediate container 3dcb0db26182
14:09:34   ---> a67bcd59b275
14:09:34  Step 5/10 : COPY ./ /app/
14:09:36   ---> 9423b7f1bde9
14:09:36  Step 6/10 : RUN gradle clean build --no-daemon
14:09:37   ---> Running in a427f088637b
14:09:38  
14:09:38  ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk
14:09:38  
14:09:38  Please set the JAVA_HOME variable in your environment to match the
14:09:38  location of your Java installation.`

**Comment by keeganwitt** [comment]
What architecture?

**Comment by keeganwitt** [comment]
Actually, I should have first clarified that my fix was to release 2 versions of the image (one which rolls back the upgrade to Ubuntu Jammy). To get this rollback, you need to use the focal variants of the image.

**Comment by keeganwitt** [comment]
I don't see this problem on any of the latest JDK 11 images
```
$ docker run --rm gradle:jdk11 sh -c 'echo $JAVA_HOME; ls $JAVA_HOME'
/opt/java/openjdk
bin
conf
include
jmods
legal
lib
man
NOTICE
release

$ docker run --rm gradle:jdk11-focal sh -c 'echo $JAVA_HOME; ls $JAVA_HOME'
/opt/java/openjdk
bin
conf
include
jmods
legal
lib
man
NOTICE
release

$ docker run --rm gradle:jdk11-alpine sh -c 'echo $JAVA_HOME; ls $JAVA_HOME'
/opt/java/openjdk
NOTICE
bin
conf
include
jmods
legal
lib
man
release

**Comment by keeganwitt** [comment]
I'll keep the Focal version for as long as it's supported. Hopefully Jammy is workable for more folks soon.

**Comment by DyBrenn** [comment]
Gotcha, my jenkins box has Docker version 19.03.8, build afacb8b. Let me know if you need anyone to help debug this problem, I can help out! Thanks for your help Ill try and see if we can switch over to gradle:jdk11-alpine in the meantime.

**Comment by keeganwitt** [comment]
Interesting. I'm on Docker 20.10.16. Lemme think the easiest way to test with Docker 19. I would like to at least understand what's happening better. I'd say both Alpine or Focal are fine. Focal won't be EOL until April 2025.

**Comment by keeganwitt** [comment]
This is the explanation I've seen linked to elsewhere https://github.com/adoptium/containers/issues/215#issuecomment-1142046045. Given that, I'm not sure that there's anything I can do inside the image itself as a workaround, unfortunately.

**Comment by luiscoms** [comment]
Same problem here, any suggestions?

```
$ docker run --rm -it gradle:jdk11 gradle

ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

$ docker run --rm -it gradle:jdk11 sh -c 'echo $JAVA_HOME; ls $JAVA_HOME'
/opt/java/openjdk
bin  conf  include  jmods  legal  lib  man  NOTICE  release
failed to resize tty, using default size

$ docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by keeganwitt** [comment]
> Same problem here, any suggestions?
> 
> ```
> $ docker run --rm -it gradle:jdk11 gradle
> 
> ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk
> 
> Please set the JAVA_HOME variable in your environment to match the
> location of your Java installation.
> 
> $ docker run --rm -it gradle:jdk11 sh -c 'echo $JAVA_HOME; ls $JAVA_HOME'
> /opt/java/openjdk
> bin  conf  include  jmods  legal  lib  man  NOTICE  release
> failed to resize tty, using default size
> 
> $ docker version
> Client:
>  Version:           18.09.6
>  API version:       1.39
>  Go version:        go1.10.8
>  Git commit:        481bc77156
>  Built:             Sat May  4 02:34:58 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          18.09.6
>   API version:      1.39 (minimum version 1.12)
>   Go version:       go1.10.8
>   Git commit:       481bc77
>   Built:            Sat May  4 02:02:43 2019
>   OS/Arch:          linux/amd64
>   Experimental:     false
> ```

Try with `gradle:jdk11-focal`.

**Comment by lidaling** [comment]
ubuntu xenial has the same error when run gralde in container .

Dockerfile as bellow:
```
FROM gradle:jd8 AS build
WORKDIR /build
COPY . .
RUN ls -al /opt
RUN gradle
```

**Comment by keeganwitt** [comment]
> ubuntu xenial has the same error when run gralde in container .
> 
> Dockerfile as bellow:
> 
> ```
> FROM gradle:jd8 AS build
> WORKDIR /build
> COPY . .
> RUN ls -al /opt
> RUN gradle
> ```

I'm not sure at the moment if all Docker 20.10 versions work with the Jammy images, but I know 20.10.16 does. If you are running an older version of Docker (which probably Xenial is), you have to use the Focal image variants.

**Comment by keeganwitt** [comment]
I tried to reproduce this problem with Docker in Docker to verify exactly which versions do and don't work, but it appears to not be reproducible there.

```
#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

stopDaemon() {
    echo "Stopping dind"
    docker stop dind || true
}
trap stopDaemon INT TERM EXIT

docker run --rm --privileged --name dind --detach docker:19-dind
sleep 8s  # wait for daemon to start
# this passes with the host Docker version of 20.10.16, but I originally expected to fail
docker exec dind docker run --rm gradle:alpine gradle --version
```

**Comment by keeganwitt** [comment]
This issue has come up so frequently (#221, #222, #223, #224, #226, #228, #229, #230, #231), I've created a page explaining: https://github.com/keeganwitt/docker-gradle/wiki/Troubleshooting:-JAVA_HOME-is-set-to-an-invalid-directory. Please let me know how the page can be improved.
