### ISSUE TITLE
Jenkins use gradle-7.4.2, gradle build execute fail.

### ISSUE THREAD

**Issue by vaclap** [keeganwitt/docker-gradle#231]
when i upgrade docker image from gradle-6.8.3 to gradle-7.4.2，jenkins or gitlab ci，can't build

**Comment by keeganwitt** [comment]
I'm going to need more information to be able to help you. What error are you seeing?

**Comment by silversoul93** [comment]
Hi @keeganwitt, I don't know if my issue is related to the @vaclap one, but I have the same problem.
When launching the build stage on the gitlab-ci, we obtain the following error:
```
Step 10/22 : RUN gradle --no-daemon
 ---> Running in bc3c096ebc1c
ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

We already built the image using this version (`gradle-7.4.2-openjdk17`) the 5th of May, 2022, and it worked.
I noticed that you updated the image after our last successful build, on 7th June 2022:
![Schermata 2022-10-14 alle 16 51 54](https://user-images.githubusercontent.com/28152586/195876703-c9e031e9-6226-4e87-bb5c-fafdbe78569b.png)

Can you help us?

Thanks 😄

**Comment by silversoul93** [comment]
Update:
we tried using the image `gradle-7.4.1-openjdk17` and it worked.
Following a little history of what we did, to make the problem more clear:
- **5th of May, 2022** &rarr; last successful build using the `gradle-7.4.2-openjdk17` image
- **7th of June, 2022** &rarr; you updated the `gradle-7.4.2-openjdk17` image
- **14th of October, 2022** &rarr; build failed with the `gradle-7.4.2-openjdk17` image
- **14th of October, 2022** &rarr; build successfully completed with the `gradle-7.4.1-openjdk17` image

**Comment by keeganwitt** [comment]
OK. It looks like this is the same problem others have encountered. This has come up frequently (#221, #222, #223, #224, #226, #227, #228, #229, #230). I've finally had a little time to create a page explaining: https://github.com/keeganwitt/docker-gradle/wiki/Troubleshooting:-JAVA_HOME-is-set-to-an-invalid-directory. Please let me know if the page can be clarified further.

**Comment by silversoul93** [comment]
Thanks for the troubleshooting page @keeganwitt.
Have a good weekend 😁
