### ISSUE TITLE
upgrade -jdk11 images to openjdk 11.0.18+

### ISSUE THREAD

**Issue by brandon1024** [keeganwitt/docker-gradle#235]
The next patch release of OpenJDK, 11.0.18, is scheduled for GA on Tuesday, January 17 2023. I'm not sure how often gradle images are upgraded to use newer releases of the JDK, so I thought I'd open this issue to keep this tracked somewhere.

The reason I bring this up is because there's a defect in the `javadoc` tool shipped in version 11.0.17 of the JDK (JDK-8222091) that prevents javadoc generation for `package-info.java` files. Our organization use these gradle images in our CI infrastructure and our javadoc task is currently failing as a result.

Thanks! :beers: 

For interested readers:
- https://wiki.openjdk.org/display/JDKUpdates/JDK11u
- https://bugs.openjdk.org/browse/JDK-8222091

**Comment by brandon1024** [comment]
Looking at your [dockerfile for jdk11](https://github.com/keeganwitt/docker-gradle/blob/master/jdk11/Dockerfile), looks like this might be out of your control entirely, haha. Bummer

**Comment by keeganwitt** [comment]
That's right. I don't handle that, the Docker Library folks do. They'll automatically update these images once the Adoptium project updates their images.

**Comment by brandon1024** [comment]
Perfect, thanks!
