### ISSUE TITLE
Update vulnerable versions of plugins

### ISSUE THREAD

**Issue by galazarevna** [keeganwitt/docker-gradle#240]
Hi, 
I found several plugins that have proven vulnerabilities. 

Here is the list of them:
```
jackson-databind-2.13.3.jar -> 2.13.4.1
aws-java-sdk-s3-1.11.948.jar -> 1.12.261
snakeyaml-1.28.jar -> 1.32
soup-1.15.1.jar -> 1.15.3
testng-6.3.1.jar -> 7.7.0
```
As of right now, in my Dockerfile I have to add some steps to download the newest versions of the plugins to replace the vulnerable ones in /opt/gradle/lib/plugins/. 

Is it possible to update the plugins to the newest versions to fix the issue?

**Comment by keeganwitt** [comment]
The plugins are managed by the upstream Gradle team. I just package what they release. There should be an upstream issue for these.
