### ISSUE TITLE
How to set init.gradle

### ISSUE THREAD

**Issue by joveth1** [keeganwitt/docker-gradle#249]
I'm writing dockerfile like this:

`FROM gradle:jdk17 AS builder`

And want to change something in  init.gradle file .What is the file location?

**Comment by keeganwitt** [comment]
https://docs.gradle.org/current/userguide/init_scripts.html describes init script locations. I don't believe any come as part of the standard Gradle distribution. There is nothing in `$GRADLE_HOME/init.d` or `$GRADLE_USER_HOME`.

**Comment by keeganwitt** [comment]
Closing as I believe there's no issue. Let me know if you believe I'm mistaken.
