### ISSUE TITLE
docker image (mac/aarch64) failing

### ISSUE THREAD

**Issue by JohannesLichtenberger** [keeganwitt/docker-gradle#268]
Hi Keegan,

Do you know if it's an issue with my docker image or maybe with the Gradle docker image or something else regarding:

https://github.com/sirixdb/sirix/issues/682

The Dockerfile is here: https://github.com/sirixdb/sirix/blob/master/Dockerfile

kind regards, and have a nice week :-)
Johannes

**Comment by JohannesLichtenberger** [comment]
Sorry, it's https://github.com/sirixdb/sirix/issues/681

**Comment by keeganwitt** [comment]
Sorry, I can't tell from what's posted there what the error might be. I'm going to need some more information to be able to help. It is still the case that Alpine images don't support ARM yet, if that helps.

**Comment by keeganwitt** [comment]
I believe this was resolved in sirixdb/sirix#681. If this isn't the case, let me know and we can re-open this issue.
