### ISSUE TITLE
Java v22 images

### ISSUE THREAD

**Issue by donalmurtagh** [keeganwitt/docker-gradle#276]
Could we get images for Java v22? Adoptium have already [released v22 builds for most platforms](https://github.com/adoptium/temurin/issues/35).

The easiest way to download the v22 builds is via the [Adoptium API](https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-two-linking-to-the-latest-jdk-or-jre)

**Comment by donalmurtagh** [comment]
I noticed that new images are only made available for LTS Java version (v8, v11, v17, v21). If that's the policy, then I guess this issue should be closed.

**Comment by keeganwitt** [comment]
That's just because the last current version was no longer supported, so I stopped publishing that image. Java 22 is on my to do list. I should have a PR up soon.

**Comment by keeganwitt** [comment]
https://github.com/keeganwitt/docker-gradle/pull/277

**Comment by keeganwitt** [comment]
It looks like the Adoptium images haven't been published to Docker Hub yet. I'll have to wait for that to happen.

**Comment by keeganwitt** [comment]
Actually, another problem we have is that Gradle doesn't yet support Java 22 for execution. So we'd need an image with both Java 21 to launch Gradle and Java 22 to use in a toolchain. Is that something that would be useful?

**Comment by keeganwitt** [comment]
What sucks is, unlike the proposal to have Java 17 and 21 in the same image, Java 22 is only supported until September of this year, so then the image will cease to receive updates because the upstream image will cease to get updates, then we need to make an image with Java 21 and 23.

**Comment by donalmurtagh** [comment]
> Actually, another problem we have is that Gradle doesn't yet support Java 22 for execution. So we'd need an image with both Java 21 to launch Gradle and Java 22 to use in a toolchain. Is that something that would be useful?

Yes!

If it's the case that the lack of JDK22 support will only affect those using a Kotlin buildscript, would there be any value in releasing a Gradle-JDK22 image for Gradle users that use a Groovy buildscript?

**Comment by keeganwitt** [comment]
> > Actually, another problem we have is that Gradle doesn't yet support Java 22 for execution. So we'd need an image with both Java 21 to launch Gradle and Java 22 to use in a toolchain. Is that something that would be useful?
> 
> Yes!
> 
> If it's the case that the lack of JDK22 support will only affect those using a Kotlin buildscript, would there be any value in releasing a Gradle-JDK22 image for Gradle users that use a Groovy buildscript?

It's my understanding it should only affect Kotlin buildscript users, but I'm trying to align this image with the policy of upstream Gradle. They say they don't support launching Gradle from Java 22, so I'm not going to either. I think the only path that keeps things the way the ly support is that joint JDK image idea.

**Comment by donalmurtagh** [comment]
@keeganwitt should I expect to see something [here](https://hub.docker.com/_/gradle/tags?page=&page_size=&ordering=&name=22), or is this still in progress?

**Comment by keeganwitt** [comment]
Still in progress (#283 will create images with both Java 21 and 22).

**Comment by keeganwitt** [comment]
Official images PR: https://github.com/docker-library/official-images/pull/16550

**Comment by donalmurtagh** [comment]
> Official images PR: [docker-library/official-images#16550](https://github.com/docker-library/official-images/pull/16550)

@keeganwitt Presumably, we have to wait until this PR is reviewed/merged before the new images are available on dockerhub?

**Comment by keeganwitt** [comment]
> > Official images PR: [docker-library/official-images#16550](https://github.com/docker-library/official-images/pull/16550)
> 
> @keeganwitt Presumably, we have to wait until this PR is reviewed/merged before the new images are available on dockerhub?

Yes, that's correct.
