### ISSUE TITLE
Add arm64 Alpine image for JDK 21

### ISSUE THREAD

**Issue by callumhauber** [keeganwitt/docker-gradle#281]
It looks like the Termurin JDK 21 Alpine image has support for arm64v8, so it should be possible to add an arm64v8 image for the JDK 21 Alpine Gradle image now (https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin#L364-L365)

```
Tags: 21.0.2_13-jdk-alpine, 21-jdk-alpine, 21-alpine
Architectures: amd64, arm64v8
GitCommit: 5ef325612fc29e529a339ea7e35e4183cf9ae888
Directory: 21/jdk/alpine
```

**Comment by keeganwitt** [comment]
Made change here: https://github.com/docker-library/official-images/pull/16502
