### ISSUE TITLE
Missing arm image gradle:8.7.0-jdk17-alpine

### ISSUE THREAD

**Issue by bob-tee** [keeganwitt/docker-gradle#286]
I have a build file with line:
`FROM gradle:8.7.0-jdk17-alpine`

I get an error saying:
```
ERROR: failed to solve: gradle:8.7.0-jdk17-alpine: failed to resolve source metadata for docker.io/library/gradle:8.7.0-jdk17-alpine: no match for platform in manifest: not found
```

I'm running on an M1 MacBook. It appears the arm version of 8.7.0-jdk17-alpine doesn't exist. I can't see it listed on this page:
https://hub.docker.com/r/arm64v8/gradle/

I do see `8.7.0-jdk21-alpine` but we aren't targeting Java 21 just yet.

As a workaround I am using 
`FROM --platform=linux/amd64 gradle:8.7.0-jdk17-alpine`

**Comment by keeganwitt** [comment]
That's correct. I didn't have that image because the upstream Java 17 Alpine image doesn't exist. 

https://hub.docker.com/r/arm64v8/eclipse-temurin/tags?page=&page_size=&ordering=&name=17-
