### ISSUE TITLE
Publish ARM version of `7.6-jdk17-alpine`

### ISSUE THREAD

**Issue by SamTheisens** [keeganwitt/docker-gradle#292]
Hi 👋 
I noticed that there aren't any ARM builds for [7.6-jdk17-alpine](https://hub.docker.com/_/gradle/tags?page=&page_size=&ordering=&name=7.6-jdk17-alpine), while there are for all the other [distributions](https://hub.docker.com/_/gradle/tags?page=&page_size=&ordering=&name=7.6-jdk17) you publish.
Any chance this could be done? Would be happy to help, but would need some pointers 🙏 .

**Comment by yosifkit** [comment]
https://github.com/keeganwitt/docker-gradle/blob/502641f3165bdd0e1381ffb6e77f567d6f6d8893/jdk17-alpine/Dockerfile#L1

From the Docker image perspective, it would require the parent image to support those architectures but `eclipse-temurin:*alpine` images (for jdk/jre less than 21) only have `amd64`.

**Comment by keeganwitt** [comment]
At the moment, there's nothing we can do here. It's something they're still working on, as I understand. If you search their GitHub [issues](https://github.com/adoptium/adoptium/issues), you'll find numerous references. The links below represent their latest status as of the time of writing.

- https://adoptium.net/supported-platforms/
- https://github.com/adoptium/temurin/issues/49
- https://github.com/adoptium/adoptium/wiki/Adoptium-Platform-Priorities
