### ISSUE TITLE
8.10.2 is missing on Docker Hub

### ISSUE THREAD

**Issue by Zuplyx** [keeganwitt/docker-gradle#299]
I saw that you added 8.10.2 in #296, but I cannot find the corresponding images on [Docker Hub](https://hub.docker.com/_/gradle/tags?name=8.10.2)

**Comment by keeganwitt** [comment]
I've been discussing the recent introduction of an `ubuntu` user on our upstream image and the fact it now sits on the 1000 uid that I was using for the `gradle` user in the official images PR: https://github.com/docker-library/official-images/pull/17612. Once that's merged, the pipeline will run to publish the new images. Sorry for the delay.
