### ISSUE TITLE
Create images based on amazonlinux 2023

### ISSUE THREAD

**Issue by alzaicko** [keeganwitt/docker-gradle#301]
We use amazonlinux and it would be nice if you could expand the images to include images based on amazonlinux2023 and amazoncoretto.

**Comment by keeganwitt** [comment]
Can you elaborate on your use case? These images are generally only used for build time, and not runtime. And it shouldn't matter if you use a different JVM at runtime than you used for compilation.

**Comment by alzaicko** [comment]
We only use images at build time, not at runtime.
In this case, we need an image with glibc, but we cannot use Debian (and derivative OS) images.

**Comment by keeganwitt** [comment]
Could you share why Debian based images don't work for you? That will give me some context for similar requests.

**Comment by alzaicko** [comment]
I didn't say that Debian-based images don't work, I just can't use them at the company I currently work for due to the way that company works.

Or I'll have to collect the images myself and keep them up to date.

**Comment by keeganwitt** [comment]
Ah, OK. I misunderstood. I thought there was a technical issue and thought I might learn something by asking :)

Amazon Corretto has an official image (which is a requirement for this image), so that's something we could do.

**Comment by keeganwitt** [comment]
I'm trying to understand now what tags we'd potentially want. There's a lot more tags than they have documented (https://github.com/corretto/corretto-docker/issues/197). I presume all we'd want is what they call "the defacto image".

**Comment by alzaicko** [comment]
I think you can do like jetty, they have a tag jetty-jdk<java_version>-amazoncoretto which is built on the basis of amazoncoretto-jdk<java_version>-al2, only they are based not on al2, but on al2023
