### ISSUE TITLE
Simple Gradle/Docker Usage Question

### ISSUE THREAD

**Issue by marcelinarcyz** [keeganwitt/docker-gradle#32]
I have a simple Java server project with a build.gradle script. `gradle run` runs perfectly on my laptop.

Ideally, there would be a reference example for writing Dockerfiles that use the gradle base Docker image. Here is my attempt for a simple project:

```
FROM gradle:4.3-jdk-alpine
ADD . /code
WORKDIR /code
CMD ["gradle", "--stacktrace", "run"]
```
I build it with `docker build -t my-server-app .`

Then I run with `docker run --rm my-server-app`

The error I get is:

```
Caused by: org.gradle.api.UncheckedIOException: Failed to create parent directory '/code/.gradle/4.3' when creating directory '/code/.gradle/4.3/fileHashes'
	at org.gradle.util.GFileUtils.mkdirs(GFileUtils.java:271)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:56)
```

Obviously, the docker container should be running as root. Why would I get this error?

**Comment by keeganwitt** [comment]
Because directories under the root directory (`/`) are owned by root (as you'd expect in a UNIX system).  If you had used the directory `/home/gradle/code`, it would work.  Alternatively, you can run as root as you said.

**Comment by Carmageddon** [comment]
Hey keeganwitt, can you please help me with very similar issue?
https://stackoverflow.com/questions/48589613/permissions-issues-in-docker-image-while-gradle-is-trying-to-write-to-an-out-dir

I am mounting my code as RW inside /home/gradle, yet I get permission issues to create out dir during build

**Comment by keeganwitt** [comment]
As questions have been answered, I'm closing this issue for now.
