### ISSUE TITLE
Build crashing on google cloud and docker hub but not locally.

### ISSUE THREAD

**Issue by usbpc** [keeganwitt/docker-gradle#44]
When trying to build my [Kotlin application using gradle as the first build stage](https://github.com/Kuroji/Kuroji-Eventrouter/blob/master/Kuroji-Eventrouter-Server/Dockerfile) the build crashes with the error   
       
    Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache()
 when run on [docker hub](https://hub.docker.com/r/usbpc/kuroji-eventrouter-server/builds/bnknnpqowwabdy82ydxiypc/) and with a google cloud build trigger. However running it locally works without any problems.

**Comment by keeganwitt** [comment]
Could it be an issue with UIDs with mounted volume?

**Comment by usbpc** [comment]
I figured it out. The use gradle had no permissions to create a folder in the working direcory. Unfortunatly google cloud build and docker hub both don't support the `--chown` option on copy so for now I'm just building as root

**Comment by keeganwitt** [comment]
Would this be solved by running as root inside container?  I'm kinda revisiting if it'd be useful to go back to root.

**Comment by usbpc** [comment]
Sorry for beeing unclear. That's what I mean I added [`USER root`](https://github.com/Kuroji/Kuroji-Eventrouter/blob/855447c5132bce27ab903355fd51609115a261e9/Kuroji-Eventrouter-Server/Dockerfile#L9) to the Dockerfile.
