### ISSUE TITLE
Remove restriction on running as root or UID 1000

### ISSUE THREAD

**Issue by l0b0** [keeganwitt/docker-gradle#46]
https://hub.docker.com/_/gradle/ mentions that if mounting a volume and not running Docker as UID 1000 you should run commands as root. This hinders development since some files within the development environment have to be dealt with as root.

As an aside, I assume you mean running Docker as UID 1000 *or root*, because running commands as the default user works fine with Docker running as root here. Or maybe I'm running into a [different issue](https://travis-ci.org/l0b0/insecure-links-highlighter/builds/346601705) (only on Travis CI):

> Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().

**Comment by keeganwitt** [comment]
What I mean is that if the volume has a uid on the host side that is not 1000, then you may need to be root inside the container.  Does that make sense?  I thought it was a good idea to avoid running the container as root in the container by default (you can specify the user to run inside the container as an argument to `run` command).  But I'm willing to reconsider if it's causing folks issues.

**Comment by l0b0** [comment]
It's great that you've used a non-root user by default. Way too many Docker image distributors think it's just fine to use root all the time. I thought the page was addressing limitation specific to this container, especially since I'm seeing the Gradle service start issue. I'll open a separate issue for that then.
