### ISSUE TITLE
Can't start Gradle when running in Travis CI as gradle user

### ISSUE THREAD

**Issue by l0b0** [keeganwitt/docker-gradle#47]
The Gradle daemon won't start when [running as the "gradle" user on Travis CI](https://travis-ci.org/l0b0/insecure-links-highlighter/builds/346601705) (`make test`):

```
> Starting Daemonon'. Working directory: /home/gradle/.gradle/daemon/4.5.1 Command: /usr/lib/jvm/java-8-openjdk-amd64/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -cp /opt/gradle/lib/gradle-launcher-4.5.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.5.1
Successfully started process 'Gradle build daemon'
> Starting Daemon> Starting Daemon> Starting Daemon> Starting Daemon> Starting Daemon> Starting Daemon> Starting Daemon> Starting Daemon> Starting Daemonpt to start the daemon took 0.936 secs.
 the daemon (pid: 33). The daemon log file: /home/gradle/.gradle/daemon/4.5.1/daemon-33.out.log
Starting build in new daemon [memory: 954.7 MB]
FAILURE: Build failed with an exception.
* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().
* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 2s
```

---

I can't reproduce this locally, but I get a possibly related issue when running as "nobody" (`make GRADLE_USER=nobody test`):

```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to load native library 'libnative-platform.so' for Linux amd64.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by keeganwitt** [comment]
Are you using volumes?

**Comment by l0b0** [comment]
Yes. You should be able to reproduce easily with the linked project.

**Comment by keeganwitt** [comment]
Have you tried setting the user to root for the Gradle container in your compose file?

**Comment by l0b0** [comment]
Yes, but I'm trying to avoid that. It pollutes the working directory with root-owned files, and I'd rather make sure all the code runs as a normal user.

**Comment by keeganwitt** [comment]
Did it work when you did that? I just wanted to verify it was permissions related and not something else.

**Comment by l0b0** [comment]
Yes, .travis.yml uses `make GRADLE_USER=root test` to work around the issue.

**Comment by keeganwitt** [comment]
So the travis user that Travis runs under is id 2000.  Since this isn't user 1000, it won't be able to read the volume.  But if you add `sudo chown 1000:1000 -R .` to the `$(extension_file)` task in Makefile, it should be able to write to the volume.

**Comment by l0b0** [comment]
Thanks for looking into this! A simple `sudo chgrp 1000 -R .` in the Travis CI configuration did the trick.
