### ISSUE TITLE
Cannot extend image

### ISSUE THREAD

**Issue by pversteijnen** [keeganwitt/docker-gradle#50]
Would like to add some componets but I am not able to switch to the root user.
Is it possible to provide the root password or an alternative? By default the gradle user is active on the image. 

Like to add a chrome headless browser to perform Serenity tests on the image as well.

apt-get update triggers an error because the gradle user does not have the rights to alter something outside the usr dir of the user.

**Comment by keeganwitt** [comment]
You should switch to root user user `USER 0` or `USER root`.  If you do that, instead of using `su`, you won't need any password.

**Comment by keeganwitt** [comment]
Closing issue, as I don't believe there's any changes currently needed.
