### ISSUE TITLE
Provide stretch slim for stretch based images

### ISSUE THREAD

**Issue by RichyHBM** [keeganwitt/docker-gradle#60]
A number of the images make use of debian stretch, these could make use of stretch slim instead and would only require installing wget and unzip. Alternatively maybe providing slim alternatives would be preferred? (As a number of images will rely on some of the base debian tools being preinstalled)

```
FROM openjdk:8-jdk-slim-stretch
RUN apt-get update && apt-get install -y --no-install-recommends wget unzip
```

**Comment by keeganwitt** [comment]
I was actually thinking of adding these last week, but I wasn't sure whether anyone was interested.
I also thought of adding the Windows ones too, though I don't have an environment to test that in at the moment.

Thank you for the PR, I'll take a look and get it merged in shortly.
