### ISSUE TITLE
amd64 builds are not available

### ISSUE THREAD

**Issue by Kleinendorst** [keeganwitt/docker-gradle#66]
This image is being used in our pipeline, but failed. 
I investigated this issue and apparently a lot of builds are not
available. The following error is printed:

```
no matching manifest for linux/amd64 in the manifest list entries
```

I tried the following images:
1. `gradle:4.10-jre-alpine`
2. `gradle:alpine`

The following image does work still: `gradle:4.9.0-jdk8-slim`, but isn't of use
to me because I rely on Alpine specific stuff (`ash`). 

I also noted the build pipeline for these images hangs: [link](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/gradle/).

**Comment by Kleinendorst** [comment]
@NeveHanter You are correct, I updated the title.

**Comment by falknerdominik** [comment]
Hi, 
do we have an estimate when this image will be available again?

**Comment by hm1rafael** [comment]
for the moment, using 4.9-alpine

**Comment by jwagnerLegacy** [comment]
Also confirming issues with gradle:jdk8-alpine and gradle:alpine

**Comment by keeganwitt** [comment]
Perhaps something happened when the latest release got tagged.  I've opened https://github.com/docker-library/official-images/issues/4789 with the Docker Library folks.

**Comment by falknerdominik** [comment]
Yep, all 4.9 images seem to work, all 4.10 images are not available.

**Comment by keeganwitt** [comment]
They're still working on an issue with their build infrastructure, but in the mean time, tianon over at Docker Library has pushed up the missing images.  You should be good to go now.
