### ISSUE TITLE
Problems pulling the image

### ISSUE THREAD

**Issue by hm1rafael** [keeganwitt/docker-gradle#67]
Trying to docker pull gradle:alpine

throws this error:
alpine: Pulling from library/gradle
no matching manifest for unknown in the manifest list entries

Other images (not gradle) are normal

**Comment by hm1rafael** [comment]
Apparently duplicate of #66

**Comment by piclemx** [comment]
Got the same problem here

**Comment by hm1rafael** [comment]
Using ```gradle:4.9-alpine``` for the time being

**Comment by keeganwitt** [comment]
Closing as dupe of #66.
