### ISSUE TITLE
Disable gradle welcome message

### ISSUE THREAD

**Issue by dnwe** [keeganwitt/docker-gradle#68]
Please could you add the following to one of the `RUN` blocks of the current Dockerfiles?
```sh
echo 'org.gradle.internal.launcher.welcomeMessageEnabled=false' \
  >> /home/gradle/gradle.properties
```
https://github.com/gradle/gradle/issues/5213

**Comment by keeganwitt** [comment]
My intent was to keep this image as vanilla as possible.  What problem does not having this property cause?  You could always change the command you run, (like `gradle --quiet  -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false`), right?

**Comment by dnwe** [comment]
Agreed it isn't a big problem and yes it is solveable in downstream images.
