### ISSUE TITLE
Gradle 5 RC Builds

### ISSUE THREAD

**Issue by yschimke** [keeganwitt/docker-gradle#74]
It seems wise to test Gradle 5 end to end before it's release.  Is the current plan to wait for 5.0 release and then provide the 5.0 images?

**Comment by keeganwitt** [comment]
If it'd be helpful for folks' testing, I can publish those.  I'd been thinking about it, but wasn't sure if there was interest.

**Comment by yschimke** [comment]
I think 1 RC could be enough to test at this point.

**Comment by keeganwitt** [comment]
Well, Gradle 5 is out now anyway, so I guess this is a moot question.  I'm gonna go ahead and close this.  I'll be updating the Gradle images shortly (tried to work on RC 5 images the other day, but there was a Docker Hub partial outage that was hindering me).
