### ISSUE TITLE
Add @docker-library-bot to auto update versions

### ISSUE THREAD

**Issue by J0WI** [keeganwitt/docker-gradle#82]
@docker-library-bot can run `update.sh` for you, just add it to the team and open a corresponding PR here: https://github.com/docker-library/oi-janky-groovy/blob/master/update.sh/vars.groovy

**Comment by keeganwitt** [comment]
How does the version environment variable get set to run on update.sh?

**Comment by J0WI** [comment]
Oh I see, this needs to be automated first. See #83

**Comment by keeganwitt** [comment]
#83 changes are good, but I don't understand how this automation works.  Would the job push commits to both [keeganwitt/docker-gradle](https://github.com/keeganwitt/docker-gradle/) and [docker-library/official-images](https://github.com/docker-library/official-images)?

**Comment by J0WI** [comment]
The bot would only run `update.sh` in this repo. [docker-library/official-images](https://github.com/docker-library/official-images) is still updated and reviewed manually by the Docker team.

**Comment by J0WI** [comment]
@keeganwitt let me know if you need any help

**Comment by keeganwitt** [comment]
Sorry for the silence.  Under this new process, I assume the bot would commit directly to this repo? Or would it open a pull request?

**Comment by J0WI** [comment]
The bot would commit directly to this repo. At times they include the changes during library updates (like in https://github.com/docker-library/official-images/pull/5439).

**Comment by tianon** [comment]
See https://github.com/docker-library/docs/issues/1248#issuecomment-395829086 for a bit more detail about what @docker-library-bot (and this `update.sh` automation) does.

I'm happy to help out here and push commits via @docker-library-bot, but if you're already monitoring the releases, I frankly don't see additional value added here for you.

**Comment by keeganwitt** [comment]
That's kind of where I was at.  I appreciate the suggestion, but if I have to keep an eye on the releases to update official-images repo anyway, than this only saves me the few minutes it takes my tests to run.
