### ISSUE TITLE
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().

### ISSUE THREAD

**Issue by opticyclic** [keeganwitt/docker-gradle#86]
My `Dockerfile` looks like this:

    FROM openjdk:8-jdk-alpine AS TEMP_BUILD_IMAGE
    ENV APP_HOME=/usr/app/
    WORKDIR $APP_HOME
    COPY build.gradle settings.gradle $APP_HOME
    COPY gradle $APP_HOME/gradle
    COPY . .
    RUN ./gradlew dependencies

And I run it just fine with

    docker build -t test:latest .

Now I want to change to the `gradle:5.2.0-jdk8-alpine` image so I don't have to download gradle using the wrapper each time. The first thing I did though was to just change the image name and check if it all works still:

    FROM gradle:5.2.0-jdk8-alpine as TEMP_BUILD_IMAGE
    ENV APP_HOME=/usr/app/
    WORKDIR $APP_HOME
    COPY build.gradle settings.gradle $APP_HOME
    COPY gradle $APP_HOME/gradle
    COPY . .
    RUN ./gradlew dependencies

But I get the error

    Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().

I still get this error if I put `USER gradle` at the top of the dockerfile.

There is something in the docs on dockerhub to changing to root user if you are mounting a volume.

But as you can see, I'm not mounting a volume.

I realise that there is some user permission issue going on but I don't understand what is different about this image that is causing it or how to modify my `Dockerfile` to fix it.

**Comment by keeganwitt** [comment]
What permission do you see when you do `ls -n` on the app directory and on the `$GRADLE_HOME` directory?  That uid/gid needs to match the uid/gid of _gradle_ user.

**Comment by opticyclic** [comment]
On `$GRADLE_HOME` we have this:

    Step 8/8 : RUN ls -n $GRADLE_HOME
     ---> Running in 4d3aa0abaab9
    total 240
    -rw-r--r--    7 0        0            55261 Feb  6 22:20 LICENSE
    -rw-r--r--    7 0        0              802 Feb  6 22:20 NOTICE
    drwxr-xr-x    2 0        0             4096 Feb  6 22:20 bin
    -rw-r--r--    7 0        0           163865 Feb  6 22:20 getting-started.html
    drwxrwxr-x    2 0        0             4096 Feb  6 22:20 init.d
    drwxr-xr-x    3 0        0             4096 Feb  6 22:20 lib
    drwxrwxr-x    2 0        0             4096 Feb  6 22:20 media

When I run `id` I see this:

    uid=1000(gradle) gid=1000(gradle) groups=1000(gradle)

Why is `$GRADLE_HOME` owned by root?

And what is different about this image (compared to the `openjdk:8-jdk-alpine` that works) that causes this problem?

**Comment by keeganwitt** [comment]
Well, the openjdk image runs as root.  I chose not to run as root in my images, to better protect users.
I think the problem would actually be in ~/.gradle, not GRADLE_HOME, now that I think of it.

**Comment by keeganwitt** [comment]
What permissions do you see on _~/.gradle_?  If you need to, you could run the container as root as a workaround (`docker run -u root`)

**Comment by opticyclic** [comment]
Are you able to duplicate this issue with the info provided?

Based on this error, I don't see how to use your images properly.

Using the workaround of running as root defeats the (admirable) benefit of not running as root in your images.

**Comment by keeganwitt** [comment]
Agreed -- that suggestion was a quick hack until we figure this out.  I was able to reproduce this locally.  In my test, some of the files in the project that was copied in were owned by root instead of gradle (I'm not sure yet why) -- a fix for this would be to chown the files after copying them.

**Comment by keeganwitt** [comment]
Oh, also -- if you are using the Gradle wrapper (gradlew), there is no need to have gradle installed in the image (either by installing yourself or using my image).  You can just use the [openjdk](https://hub.docker.com/_/openjdk/) image.

**Comment by keeganwitt** [comment]
Closing the issue for now, as I believe the issue should be resolved.  If you're still having problems, let me know and we can re-open.
