### ISSUE TITLE
May no longer need bash after Gradle 3.2.1

### ISSUE THREAD

**Issue by eriwen** [keeganwitt/docker-gradle#9]
In Gradle 3.2.1 we converted the Gradle Wrapper to run under plain `sh`, so you may consider removing it from the images.

**Comment by keeganwitt** [comment]
I'm dreadfully sorry for the late response.  Somehow notifications got disabled on this repo and I had no idea issues were being opened.  It's back on now, but if I don't respond in the future, feel free to yell at me on [email](mailto:keeganwitt@gmail.com) or [Twitter](https://twitter.com/keeganwitt).

I'll test this out.  Thanks for the heads-up.

**Comment by keeganwitt** [comment]
PR for this issue: #22.
